/**
 * Error and Success Codes System
 *
 * This file defines all error and success codes used throughout the API.
 * Frontend should use these codes to display user-friendly messages in multiple languages.
 *
 * Code format:
 * - Error codes: ERROR_<MODULE>_<ACTION>_<REASON>
 * - Success codes: SUCCESS_<MODULE>_<ACTION>
 *
 * Example:
 * - ERROR_REGISTRATION_CREATE_DUPLICATE_EMAIL
 * - SUCCESS_REGISTRATION_CREATED
 */

// ============================================================================
// AUTHENTICATION CODES
// ============================================================================

export const AUTH_CODES = {
  // Success codes
  SUCCESS_AUTH_REGISTERED: 'SUCCESS_AUTH_REGISTERED',
  SUCCESS_AUTH_LOGGED_IN: 'SUCCESS_AUTH_LOGGED_IN',
  SUCCESS_AUTH_LOGGED_OUT: 'SUCCESS_AUTH_LOGGED_OUT',
  SUCCESS_AUTH_TOKEN_REFRESHED: 'SUCCESS_AUTH_TOKEN_REFRESHED',
  SUCCESS_AUTH_PROFILE_RETRIEVED: 'SUCCESS_AUTH_PROFILE_RETRIEVED',
  SUCCESS_AUTH_PROFILE_UPDATED: 'SUCCESS_AUTH_PROFILE_UPDATED',

  // Error codes
  ERROR_AUTH_INVALID_CREDENTIALS: 'ERROR_AUTH_INVALID_CREDENTIALS',
  ERROR_AUTH_EMAIL_EXISTS: 'ERROR_AUTH_EMAIL_EXISTS',
  ERROR_AUTH_TOKEN_EXPIRED: 'ERROR_AUTH_TOKEN_EXPIRED',
  ERROR_AUTH_TOKEN_INVALID: 'ERROR_AUTH_TOKEN_INVALID',
  ERROR_AUTH_TOKEN_MISSING: 'ERROR_AUTH_TOKEN_MISSING',
  ERROR_AUTH_UNAUTHORIZED: 'ERROR_AUTH_UNAUTHORIZED',
  ERROR_AUTH_REFRESH_TOKEN_INVALID: 'ERROR_AUTH_REFRESH_TOKEN_INVALID',
  ERROR_AUTH_PASSWORD_WEAK: 'ERROR_AUTH_PASSWORD_WEAK',
  ERROR_AUTH_PHONE_EXISTS: 'ERROR_AUTH_PHONE_EXISTS',
  ERROR_AUTH_USER_NOT_FOUND: 'ERROR_AUTH_USER_NOT_FOUND',
  ERROR_AUTH_RESET_TOKEN_INVALID: 'ERROR_AUTH_RESET_TOKEN_INVALID',
  ERROR_AUTH_ADMIN_REQUIRED: 'ERROR_AUTH_ADMIN_REQUIRED',
  ERROR_AUTH_SUPER_ADMIN_REQUIRED: 'ERROR_AUTH_SUPER_ADMIN_REQUIRED',
  ERROR_AUTH_ACCOUNT_LOCKED: 'ERROR_AUTH_ACCOUNT_LOCKED',
} as const;

// ============================================================================
// EVENTS CODES
// ============================================================================

export const EVENTS_CODES = {
  // Success codes
  SUCCESS_EVENTS_CREATED: 'SUCCESS_EVENTS_CREATED',
  SUCCESS_EVENTS_UPDATED: 'SUCCESS_EVENTS_UPDATED',
  SUCCESS_EVENTS_DELETED: 'SUCCESS_EVENTS_DELETED',
  SUCCESS_EVENTS_RETRIEVED: 'SUCCESS_EVENTS_RETRIEVED',
  SUCCESS_EVENTS_LIST_RETRIEVED: 'SUCCESS_EVENTS_LIST_RETRIEVED',

  // Error codes
  ERROR_EVENTS_NOT_FOUND: 'ERROR_EVENTS_NOT_FOUND',
  ERROR_EVENTS_INVALID_ID: 'ERROR_EVENTS_INVALID_ID',
  ERROR_EVENTS_PAST_DATE: 'ERROR_EVENTS_PAST_DATE',
  ERROR_EVENTS_FORBIDDEN: 'ERROR_EVENTS_FORBIDDEN',
  ERROR_EVENTS_CAPACITY_INVALID: 'ERROR_EVENTS_CAPACITY_INVALID',
} as const;

// ============================================================================
// REGISTRATIONS CODES
// ============================================================================

export const REGISTRATIONS_CODES = {
  // Success codes
  SUCCESS_REGISTRATION_CREATED: 'SUCCESS_REGISTRATION_CREATED',
  SUCCESS_REGISTRATION_CANCELLED: 'SUCCESS_REGISTRATION_CANCELLED',
  SUCCESS_REGISTRATION_RETRIEVED: 'SUCCESS_REGISTRATION_RETRIEVED',
  SUCCESS_REGISTRATIONS_LIST_RETRIEVED: 'SUCCESS_REGISTRATIONS_LIST_RETRIEVED',
  SUCCESS_REGISTRATION_REFUNDED: 'SUCCESS_REGISTRATION_REFUNDED',
  SUCCESS_REGISTRATION_PAYMENT_SYNCED: 'SUCCESS_REGISTRATION_PAYMENT_SYNCED',
  SUCCESS_REGISTRATION_PAYMENT_LINK_RETRIEVED: 'SUCCESS_REGISTRATION_PAYMENT_LINK_RETRIEVED',
  SUCCESS_REGISTRATION_PARTICIPANTS_RETRIEVED: 'SUCCESS_REGISTRATION_PARTICIPANTS_RETRIEVED',

  // Error codes
  ERROR_REGISTRATION_NOT_FOUND: 'ERROR_REGISTRATION_NOT_FOUND',
  ERROR_REGISTRATION_INVALID_ID: 'ERROR_REGISTRATION_INVALID_ID',
  ERROR_REGISTRATION_DUPLICATE_EMAIL: 'ERROR_REGISTRATION_DUPLICATE_EMAIL',
  ERROR_REGISTRATION_DUPLICATE_USER: 'ERROR_REGISTRATION_DUPLICATE_USER',
  ERROR_REGISTRATION_PENDING_PAYMENT: 'ERROR_REGISTRATION_PENDING_PAYMENT',
  ERROR_REGISTRATION_EVENT_FULL: 'ERROR_REGISTRATION_EVENT_FULL',
  ERROR_REGISTRATION_EVENT_PAST: 'ERROR_REGISTRATION_EVENT_PAST',
  ERROR_REGISTRATION_FORBIDDEN: 'ERROR_REGISTRATION_FORBIDDEN',
  ERROR_REGISTRATION_ALREADY_CANCELLED: 'ERROR_REGISTRATION_ALREADY_CANCELLED',
  ERROR_REGISTRATION_NO_PAYMENT: 'ERROR_REGISTRATION_NO_PAYMENT',
  ERROR_REGISTRATION_PAYMENT_LINK_NOT_FOUND: 'ERROR_REGISTRATION_PAYMENT_LINK_NOT_FOUND',
  ERROR_REGISTRATION_PRICE_NOT_CONFIGURED: 'ERROR_REGISTRATION_PRICE_NOT_CONFIGURED',
} as const;

// ============================================================================
// PAYMENTS CODES
// ============================================================================

export const PAYMENTS_CODES = {
  // Success codes
  SUCCESS_PAYMENT_CREATED: 'SUCCESS_PAYMENT_CREATED',
  SUCCESS_PAYMENT_COMPLETED: 'SUCCESS_PAYMENT_COMPLETED',
  SUCCESS_PAYMENT_REFUNDED: 'SUCCESS_PAYMENT_REFUNDED',
  SUCCESS_PAYMENT_STATUS_RETRIEVED: 'SUCCESS_PAYMENT_STATUS_RETRIEVED',

  // Error codes
  ERROR_PAYMENT_NOT_FOUND: 'ERROR_PAYMENT_NOT_FOUND',
  ERROR_PAYMENT_INVALID_ID: 'ERROR_PAYMENT_INVALID_ID',
  ERROR_PAYMENT_ALREADY_COMPLETED: 'ERROR_PAYMENT_ALREADY_COMPLETED',
  ERROR_PAYMENT_ALREADY_REFUNDED: 'ERROR_PAYMENT_ALREADY_REFUNDED',
  ERROR_PAYMENT_FAILED: 'ERROR_PAYMENT_FAILED',
  ERROR_PAYMENT_EXTERNAL_API_ERROR: 'ERROR_PAYMENT_EXTERNAL_API_ERROR',
  ERROR_PAYMENT_INVOICE_ID_MISSING: 'ERROR_PAYMENT_INVOICE_ID_MISSING',
} as const;

// ============================================================================
// PROMO CODES CODES
// ============================================================================

export const PROMO_CODES_CODES = {
  // Success codes
  SUCCESS_PROMO_CODE_VALIDATED: 'SUCCESS_PROMO_CODE_VALIDATED',
  SUCCESS_PROMO_CODE_RETRIEVED: 'SUCCESS_PROMO_CODE_RETRIEVED',
  SUCCESS_PROMO_CODES_ADMIN_LIST_RETRIEVED: 'SUCCESS_PROMO_CODES_ADMIN_LIST_RETRIEVED',
  SUCCESS_PROMO_CODE_ADMIN_CREATED: 'SUCCESS_PROMO_CODE_ADMIN_CREATED',
  SUCCESS_PROMO_CODE_ADMIN_UPDATED: 'SUCCESS_PROMO_CODE_ADMIN_UPDATED',

  // Error codes
  ERROR_PROMO_CODE_NOT_FOUND: 'ERROR_PROMO_CODE_NOT_FOUND',
  ERROR_PROMO_CODE_DUPLICATE: 'ERROR_PROMO_CODE_DUPLICATE',
  ERROR_PROMO_CODE_INVALID: 'ERROR_PROMO_CODE_INVALID',
  ERROR_PROMO_CODE_EXPIRED: 'ERROR_PROMO_CODE_EXPIRED',
  ERROR_PROMO_CODE_USAGE_LIMIT_REACHED: 'ERROR_PROMO_CODE_USAGE_LIMIT_REACHED',
  ERROR_PROMO_CODE_NOT_APPLICABLE: 'ERROR_PROMO_CODE_NOT_APPLICABLE',
} as const;

// ============================================================================
// ADMIN USERS CODES
// ============================================================================

export const ADMIN_USERS_CODES = {
  // Success codes
  SUCCESS_ADMIN_USERS_LIST_RETRIEVED: 'SUCCESS_ADMIN_USERS_LIST_RETRIEVED',
  SUCCESS_ADMIN_USER_RETRIEVED: 'SUCCESS_ADMIN_USER_RETRIEVED',
  SUCCESS_ADMIN_USER_UPDATED: 'SUCCESS_ADMIN_USER_UPDATED',
  SUCCESS_ADMIN_USER_DELETED: 'SUCCESS_ADMIN_USER_DELETED',
  SUCCESS_ADMIN_USER_REGISTRATION_CANCELLED: 'SUCCESS_ADMIN_USER_REGISTRATION_CANCELLED',
  SUCCESS_ADMIN_USERS_EXPORTED: 'SUCCESS_ADMIN_USERS_EXPORTED',

  // Error codes
  ERROR_ADMIN_USER_NOT_FOUND: 'ERROR_ADMIN_USER_NOT_FOUND',
  ERROR_ADMIN_USER_EMAIL_EXISTS: 'ERROR_ADMIN_USER_EMAIL_EXISTS',
  ERROR_ADMIN_USER_PHONE_EXISTS: 'ERROR_ADMIN_USER_PHONE_EXISTS',
  ERROR_ADMIN_USER_CANNOT_DELETE_SELF: 'ERROR_ADMIN_USER_CANNOT_DELETE_SELF',
  ERROR_ADMIN_USER_CANNOT_DELETE_LAST_SUPER_ADMIN:
    'ERROR_ADMIN_USER_CANNOT_DELETE_LAST_SUPER_ADMIN',
  ERROR_ADMIN_USER_REGISTRATION_NOT_FOUND: 'ERROR_ADMIN_USER_REGISTRATION_NOT_FOUND',
  ERROR_ADMIN_USER_REGISTRATION_ALREADY_CANCELLED:
    'ERROR_ADMIN_USER_REGISTRATION_ALREADY_CANCELLED',
} as const;

// ============================================================================
// ADMIN REGISTRATIONS CODES
// ============================================================================

export const ADMIN_REGISTRATIONS_CODES = {
  // Success codes
  SUCCESS_ADMIN_REGISTRATIONS_LIST_RETRIEVED: 'SUCCESS_ADMIN_REGISTRATIONS_LIST_RETRIEVED',
  SUCCESS_ADMIN_REGISTRATION_RETRIEVED: 'SUCCESS_ADMIN_REGISTRATION_RETRIEVED',
  SUCCESS_ADMIN_REGISTRATION_CANCELLED: 'SUCCESS_ADMIN_REGISTRATION_CANCELLED',
  SUCCESS_ADMIN_REGISTRATIONS_EXPORTED: 'SUCCESS_ADMIN_REGISTRATIONS_EXPORTED',

  // Error codes
  ERROR_ADMIN_REGISTRATION_NOT_FOUND: 'ERROR_ADMIN_REGISTRATION_NOT_FOUND',
  ERROR_ADMIN_REGISTRATION_INVALID_ID: 'ERROR_ADMIN_REGISTRATION_INVALID_ID',
  ERROR_ADMIN_REGISTRATION_ALREADY_CANCELLED: 'ERROR_ADMIN_REGISTRATION_ALREADY_CANCELLED',
} as const;

// ============================================================================
// ADMIN ANALYTICS CODES
// ============================================================================

export const ADMIN_ANALYTICS_CODES = {
  // Success codes
  SUCCESS_ANALYTICS_SUMMARY_RETRIEVED: 'SUCCESS_ANALYTICS_SUMMARY_RETRIEVED',
  SUCCESS_ANALYTICS_TIMESERIES_RETRIEVED: 'SUCCESS_ANALYTICS_TIMESERIES_RETRIEVED',
  SUCCESS_ANALYTICS_DEMOGRAPHICS_RETRIEVED: 'SUCCESS_ANALYTICS_DEMOGRAPHICS_RETRIEVED',
  SUCCESS_ANALYTICS_BY_EVENT_RETRIEVED: 'SUCCESS_ANALYTICS_BY_EVENT_RETRIEVED',

  // Error codes
  ERROR_ANALYTICS_INVALID_RANGE: 'ERROR_ANALYTICS_INVALID_RANGE',
} as const;

// ============================================================================
// AUDIT LOGS CODES
// ============================================================================

export const AUDIT_LOGS_CODES = {
  SUCCESS_AUDIT_LOGS_RETRIEVED: 'SUCCESS_AUDIT_LOGS_RETRIEVED',
  ERROR_AUDIT_LOGS_FORBIDDEN: 'ERROR_AUDIT_LOGS_FORBIDDEN',
} as const;

// ============================================================================
// VALIDATION CODES
// ============================================================================

export const VALIDATION_CODES = {
  // Error codes
  ERROR_VALIDATION_FAILED: 'ERROR_VALIDATION_FAILED',
  ERROR_VALIDATION_REQUIRED_FIELD: 'ERROR_VALIDATION_REQUIRED_FIELD',
  ERROR_VALIDATION_INVALID_EMAIL: 'ERROR_VALIDATION_INVALID_EMAIL',
  ERROR_VALIDATION_INVALID_PHONE: 'ERROR_VALIDATION_INVALID_PHONE',
  ERROR_VALIDATION_INVALID_DATE: 'ERROR_VALIDATION_INVALID_DATE',
  ERROR_VALIDATION_INVALID_OBJECT_ID: 'ERROR_VALIDATION_INVALID_OBJECT_ID',
  ERROR_VALIDATION_STRING_TOO_SHORT: 'ERROR_VALIDATION_STRING_TOO_SHORT',
  ERROR_VALIDATION_STRING_TOO_LONG: 'ERROR_VALIDATION_STRING_TOO_LONG',
  ERROR_VALIDATION_NUMBER_TOO_SMALL: 'ERROR_VALIDATION_NUMBER_TOO_SMALL',
  ERROR_VALIDATION_NUMBER_TOO_LARGE: 'ERROR_VALIDATION_NUMBER_TOO_LARGE',
} as const;

// ============================================================================
// GENERAL CODES
// ============================================================================

export const GENERAL_CODES = {
  // Success codes
  SUCCESS_OPERATION_COMPLETED: 'SUCCESS_OPERATION_COMPLETED',
  SUCCESS_DATA_RETRIEVED: 'SUCCESS_DATA_RETRIEVED',

  // Error codes
  ERROR_INTERNAL_SERVER: 'ERROR_INTERNAL_SERVER',
  ERROR_NOT_FOUND: 'ERROR_NOT_FOUND',
  ERROR_FORBIDDEN: 'ERROR_FORBIDDEN',
  ERROR_BAD_REQUEST: 'ERROR_BAD_REQUEST',
  ERROR_RATE_LIMIT_EXCEEDED: 'ERROR_RATE_LIMIT_EXCEEDED',
} as const;

// ============================================================================
// ALL CODES (for type safety)
// ============================================================================

export const API_CODES = {
  ...AUTH_CODES,
  ...EVENTS_CODES,
  ...REGISTRATIONS_CODES,
  ...PAYMENTS_CODES,
  ...PROMO_CODES_CODES,
  ...ADMIN_USERS_CODES,
  ...ADMIN_REGISTRATIONS_CODES,
  ...ADMIN_ANALYTICS_CODES,
  ...AUDIT_LOGS_CODES,
  ...VALIDATION_CODES,
  ...GENERAL_CODES,
} as const;

export type ErrorCode = (typeof API_CODES)[keyof typeof API_CODES];
export type SuccessCode = (typeof API_CODES)[keyof typeof API_CODES];
